-- Practice sub-type: easy day vs. workout vs. long run.
-- Only meaningful when events.type = 'practice'; '' means "unspecified practice".
ALTER TABLE events ADD COLUMN kind TEXT NOT NULL DEFAULT ''
  CHECK (kind IN ('', 'easy', 'workout', 'long_run'));

-- 1 for practices generated by the "traditional week" formatter in the admin
-- panel. Un-ticking a week only deletes rows with auto = 1, so hand-made
-- events on those days are never destroyed.
ALTER TABLE events ADD COLUMN auto INTEGER NOT NULL DEFAULT 0;
